services:
  postgres:
    container_name: postgres-nextjs-starter
    image: postgres:latest
    environment:
      - POSTGRES_DATABASE=${POSTGRES_DATABASE?error}
      - POSTGRES_USER=${POSTGRES_USER?error}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?error}
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/postgres_data:/var/lib/postgresql/data
